import { useState, useEffect } from "react";
import { loadFuriganaMap, getFuriganaHtml, isFuriganaReady } from "../lib/furigana";

interface RubyTextProps {
  text: string;
  className?: string;
}

/**
 * Renders Japanese text with furigana (ruby annotations) above kanji.
 * Falls back to plain text while the furigana map is loading.
 */
export default function RubyText({ text, className }: RubyTextProps) {
  const [ready, setReady] = useState(isFuriganaReady());

  useEffect(() => {
    if (!ready) {
      loadFuriganaMap().then(() => setReady(true));
    }
  }, [ready]);

  if (!ready) {
    return <span className={className}>{text}</span>;
  }

  const html = getFuriganaHtml(text);
  if (!html) {
    return <span className={className}>{text}</span>;
  }

  return (
    <span
      className={className}
      // Content is generated by our own pykakasi script — safe HTML
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
